# tasks related to installing apache and php
# all things specific to librenms is elsewhere
- name: Install apache2 and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2

- name: Disable apache modules.
  apache2_module:
    state: absent
    name: "{{ item }}"
  with_items:
    - mpm_event
  notify:
    - restart apache2 service

- name: Enable apache modules.
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - php7.0
    - mpm_prefork
    - rewrite
  notify:
    - restart apache2 service

- name: get php modules
  command: "php -m"
  register: php_mods_enabled
  changed_when: False

- name: Enable PHP modules.
  command: phpenmod mcrypt
  when: "'mcrypt' not in php_mods_enabled.stdout_lines"
  notify:
    - restart apache2 service

- name: "Check for disables defaultsite: {{ apache_default_site}}"
  command: "a2query -s {{ apache_default_site }} -q"
  changed_when: False
  failed_when: False
  register: apache_default_check

- name: Disable apache2 default site
  command: "a2dissite {{ apache_default_site }}"
  when: not apache_default_check.rc
  notify:
    - restart apache2 service
